services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
     
  spring-app:
    image: chaimaboussaidi2000/ekara_robot_management_service:latest
    ports:
      - "9090:9090"
    depends_on:
      - zipkin
    environment:
      # Add necessary environment variables here
      - ZIPKIN_BASE_URL=http://zipkin:9411
